# mysql
mysql:
  container_name: local-mysql
  image: mysql:latest
  restart: always
  ports:
   - "3306:3306"
  volumes:
   - ./mysql/conf.d:/etc/mysql/conf.d
   - ./mysql/data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: hs@19931028

# rabbitmq
rabbitmq:
  container_name: local-rabbitmq
  image: rabbitmq:latest
  restart: always
  ports:
   - "5672:5672"
   - "15672:15672"
  volumes:
   - ./rabbitmq/data:/var/lib/rabbitmq
  environment:
    RABBITMQ_DEFAULT_USER: root
    RABBITMQ_DEFAUTL_PASS: hs@19931028

# redis
redis:
  container_name: local-redis
  image: redis:latest
  restart: always
  ports:
   - "6379:6379"
  volumes:
   - ./redis/data:/data

# nginx
nginx:
  container_name: local-nginx
  image: nginx:latest
  restart: always
  ports:
   - "80:80"
  